### ISSUE TITLE
error dso

### ISSUE THREAD

**Issue by vigneshgig** [NVlabs/neuralrgbd#8]
sh local_test_LBA.sh
Parsing arguments ...
copying the images..
/bin/sh: 1: ../third_party/dso/build/bin/dso_dataset: not found
Traceback (most recent call last):
  File "run_dso.py", line 77, in <module>
    main() 
  File "run_dso.py", line 68, in main
    mode = 1, preset = 2, nogui = 1, use_existing = False ) 
  File "/home/administrator/Depth_testing/neuralrgbd/code/DSO/dso_io.py", line 255, in run_DSO
    RTs_cam_to_world = _read_camera_poses( './result.txt', if_invert= if_invert )
  File "/home/administrator/Depth_testing/neuralrgbd/code/DSO/dso_io.py", line 103, in _read_camera_poses
    with open(result_txt_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: './result.txt'
Parsing the arguments...
Initnializing the KV-Net
bn_running_avg = 0
 RefineNet_UNet2D: init conv2d
 RefineNet_UNet2D: init conv2d
 init transposed 2d
 RefineNet_UNet2D: init conv2d
 RefineNet_UNet2D: init conv2d
 init transposed 2d
 RefineNet_UNet2D: init conv2d
 RefineNet_UNet2D: init conv2d
 RefineNet_UNet2D: init conv2d
KV-Net initialization:
with R-net: True
	refinement name: DPV
loading KV_net at ./saved_models/kvnet_scannet.tar
Done
Getting the paths for traj_0
Done
init initial pose from DSO estimations ...
Traceback (most recent call last):
  File "test_KVNet_LBA.py", line 532, in <module>
    main()
  File "test_KVNet_LBA.py", line 302, in main
    min_idx = args.min_frame_idx, max_idx = args.max_frame_idx)
  File "test_KVNet_LBA.py", line 83, in init_traj_extMs
    dso_Rts = dso_io._read_camera_poses( dso_res_path, if_filter = if_filter )
  File "/home/administrator/Depth_testing/neuralrgbd/code/DSO/dso_io.py", line 103, in _read_camera_poses
    with open(result_txt_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dso_res/result_dso.txt'

**Comment by cxlcl** [comment]
Did you build dso and get the binary at 

> ../third_party/dso/build/bin/dso_dataset
?
